<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.0.0</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<groupId>de.ma</groupId>
	<artifactId>analyze</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<name>analyze</name>
	<description>Source code analysis</description>
    <url>https://github.com/martinabsmeier/analyze</url>
    <inceptionYear>2025</inceptionYear>

	<licenses>
        <license>
            <name>Apache License Version 2.0, January 2004</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
	</licenses>

	<developers>
        <developer>
            <name>Martin Absmeier</name>
            <email>martin.absmeier@gmx.de</email>
            <roles>
                <role>Lead Developer</role>
            </roles>
            <timezone>Europe/Berlin</timezone>
        </developer>
	</developers>

    <scm>
        <connection>scm:git:https://github.com/martinabsmeier/analyze.git</connection>
        <developerConnection>scm:git:ssh://git@github.com/martinabsmeier/analyze.git</developerConnection>
        <tag>HEAD</tag>
        <url>https://github.com/martinabsmeier/analyze/tree/main</url>
    </scm>

	<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>21</java.version>

        <!-- Dependency versions -->
        <antlr4.version>4.13.1</antlr4.version>
	</properties>

	<dependencies>
        <!-- Application dependencies -->
        <dependency>
            <groupId>org.antlr</groupId>
            <artifactId>antlr4</artifactId>
            <version>${antlr4.version}</version>
        </dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>

		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<scope>runtime</scope>
		</dependency>

        <!-- Compile dependencies -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
            <scope>compile</scope>
		</dependency>

        <!-- Test dependencies -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa-test</artifactId>
			<scope>test</scope>
		</dependency>

        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>

            <plugin>
                <groupId>org.antlr</groupId>
                <artifactId>antlr4-maven-plugin</artifactId>
                <version>${antlr4.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>antlr4</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <listener>true</listener>
                    <visitor>true</visitor>
                </configuration>
            </plugin>
        </plugins>
	</build>
</project>
